### ISSUE TITLE
Connections never closed

### ISSUE THREAD

**Issue by agasser** [Spksh/TentacleSoftware.Telnet#2]
The Telnet class creates System.Net.TcpClient connections and calls GetStream, but never closes the returned stream. The Telnet class's interface should provide the ability to close the connection, and it should close all streams retrieved from GetStream.

We have confirmed this behavior (in our production app by accident) by opening a new connection with Telnet every 30 seconds. The connections accumulate and never get closed.

See [TcpClient documentation](http://msdn.microsoft.com/en-us/library/system.net.sockets.tcpclient.getstream(v=vs.110).aspx):
> You must close the NetworkStream when you are through sending and receiving data. Closing TcpClient does not release the NetworkStream.

**Comment by Spksh** [comment]
Now throwing an InvalidOperationException on Connect() if we were previously connected.
